from __future__ import annotations

import json
import re
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from app.gateway.schemas import ChatMessage, ChatRequest
from app.local_models.provider import LocalProvider
from app.memory.context_builder import ContextBuilder
from app.repositories.graph_repository import GraphRepository


PlannerDecision = Literal["continue", "retry", "change_strategy", "ask_user", "finish"]


class FollowUpPlan(BaseModel):
    """Decision and optional stateless cloud prompt generated by Qwen."""

    model_config = ConfigDict(extra="forbid")

    decision: PlannerDecision
    reason: str = Field(min_length=1, max_length=2000)
    next_step: str = Field(min_length=1, max_length=500)
    cloud_prompt: str | None = Field(default=None, max_length=4000)
    progress_score: float = Field(ge=0.0, le=1.0)
    confidence: float = Field(ge=0.0, le=1.0)


class FollowUpPlanner:
    """Use Qwen to maintain continuity after each observation without cloud state."""

    _code_markers = re.compile(
        r"```|\b(?:shell|bash|python|javascript|typescript)\s*:\s|\b(?:rm|sudo|pip|npm|git)\s+-",
        re.IGNORECASE,
    )
    _prompt_decisions = {"continue", "retry", "change_strategy"}

    def __init__(self, provider: LocalProvider, context_builder: ContextBuilder | None = None) -> None:
        self.provider = provider
        self.context_builder = context_builder or ContextBuilder(GraphRepository())

    def plan(
        self,
        *,
        task_id: str,
        execution_report: dict[str, Any],
        git_diff: str = "",
        test_results: dict[str, Any] | list[Any] | None = None,
        errors: list[str] | None = None,
        workflow_state: dict[str, Any] | None = None,
        progress: dict[str, Any] | None = None,
        constraints: list[str] | None = None,
    ) -> FollowUpPlan:
        graph_context = self._graph_context(task_id)
        prompt = self._build_prompt(
            task_id=task_id,
            graph_context=graph_context,
            execution_report=execution_report,
            git_diff=git_diff,
            test_results=test_results or {},
            errors=errors or [],
            workflow_state=workflow_state or {},
            progress=progress or {},
            constraints=constraints or [],
        )
        response = self.provider.chat(ChatRequest(messages=[ChatMessage(role="user", content=prompt)]))
        return self.validate_response(response.content)

    def validate_response(self, content: str) -> FollowUpPlan:
        if not isinstance(content, str) or not content.strip():
            raise ValueError("Follow-up plan must be non-empty JSON")
        try:
            payload = json.loads(content)
        except json.JSONDecodeError as error:
            raise ValueError("Follow-up plan must contain JSON only") from error
        if not isinstance(payload, dict):
            raise ValueError("Follow-up plan must be a JSON object")
        try:
            plan = FollowUpPlan.model_validate(payload)
        except ValidationError as error:
            raise ValueError("Follow-up plan does not match the planner schema") from error
        self._validate_plan(plan)
        return plan

    def _graph_context(self, task_id: str) -> dict[str, Any]:
        try:
            return self.context_builder.build_context(task_id)
        except ValueError:
            return {"task": task_id, "files": [], "decisions": [], "errors": [], "graph_memory": []}

    @classmethod
    def _validate_plan(cls, plan: FollowUpPlan) -> None:
        values = (plan.reason, plan.next_step, plan.cloud_prompt or "")
        if any(cls._code_markers.search(value) for value in values):
            raise ValueError("Follow-up plans must not contain executable code or shell commands")
        if plan.decision in cls._prompt_decisions and not plan.cloud_prompt:
            raise ValueError(f"{plan.decision} requires a cloud_prompt")
        if plan.decision in {"ask_user", "finish"} and plan.cloud_prompt:
            raise ValueError(f"{plan.decision} must not include a cloud_prompt")

    @staticmethod
    def _build_prompt(
        *,
        task_id: str,
        graph_context: dict[str, Any],
        execution_report: dict[str, Any],
        git_diff: str,
        test_results: dict[str, Any] | list[Any],
        errors: list[str],
        workflow_state: dict[str, Any],
        progress: dict[str, Any],
        constraints: list[str],
    ) -> str:
        return (
            "You are Qwen, the local continuity planner. A cloud model is stateless and never decides workflow. "
            "After this observation, choose exactly one decision: continue, retry, change_strategy, ask_user, finish. "
            "Return JSON only with exactly these keys: decision, reason, next_step, cloud_prompt, progress_score, confidence. "
            "Never output code, shell commands, file edits, or action objects. "
            "cloud_prompt is natural-language context for a stateless cloud worker and must be null for ask_user or finish.\n\n"
            f"TASK ID\n{task_id}\n\n"
            f"BRAIN GRAPH\n{json.dumps(graph_context, sort_keys=True)}\n\n"
            f"EXECUTION REPORT\n{json.dumps(execution_report, sort_keys=True)}\n\n"
            f"GIT DIFF\n{git_diff or 'none'}\n\n"
            f"TEST RESULTS\n{json.dumps(test_results, sort_keys=True)}\n\n"
            f"ERRORS\n{json.dumps(errors)}\n\n"
            f"WORKFLOW STATE\n{json.dumps(workflow_state, sort_keys=True)}\n\n"
            f"PROGRESS\n{json.dumps(progress, sort_keys=True)}\n\n"
            f"CONSTRAINTS\n{json.dumps(constraints)}"
        )
